description: "Copy Snapshot"
schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  SnapshotId:
    type: "String"
    description: "(Required) The ID of the EBS snapshot to copy."
  SourceRegion:
    type: "String"
    description: "(Required) The ID of the region that contains the snapshot to be
       copied."
  Description:
    type: "String"
    description: "(Optional) A description for the EBS snapshot."
    default: ""
  LambdaAssumeRole:
    type: "String"
    description: "(Optional) The ARN of the role assumed by lambda"
    default: ""
  AutomationAssumeRole:
    default: ""
    type: "String"
    description: "(Optional) The ARN of the role that allows Automation to perform
       the actions on your behalf."
mainSteps:
- action: "aws:createStack"
  inputs:
    StackName: "CopySnapshotStack{{automation:EXECUTION_ID}}"
    TemplateBody: "AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  LambdaAssumeRoleNotSpecified:

          Fn::Or:
    - Fn::Equals:
      - Ref: LambdaRoleArn
      - ''
  
        - Fn::Equals:
      - Ref: LambdaRoleArn
      - undefined
Parameters:

        LambdaName:
    Description: The lambda function name
    Type: String

        LambdaRoleArn:
    Default: ''
    Description: The ARN of the role that
       allows Lambda created by Automation to perform
      the action on your behalf

          Type: String
Resources:
  CopySnapshotLambda:
    Properties:
    
        Code:
        ZipFile: "#
# Copyright 2018 Amazon.com, Inc. or its affiliates.
       All Rights
           Reserved.
#
# Permission is hereby granted,
       free of charge, to any person
           obtaining a copy of this
#
       software and associated documentation files
           (the "Software
      "), to deal in the Software
# without restriction, including
        
         without limitation the rights to use, copy, modify,
# merge, publish,
      
           distribute, sublicense, and/or sell copies of the Software, and
       to
#
           permit persons to whom the Software is furnished to
       do so.
#
# THE SOFTWARE
           IS PROVIDED "AS IS", WITHOUT
       WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,

          # INCLUDING BUT
       NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
          
       FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE

                 AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
       OR OTHER
           LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT,
       TORT OR OTHERWISE, ARISING
           FROM, OUT OF OR IN CONNECTION WITH
       THE
# SOFTWARE OR THE USE OR OTHER
           DEALINGS IN THE SOFTWARE.
      n#
import boto3


def handler(event, context):

          tec2_client
       = boto3.client("ec2")

tsnapshot_id = event["SnapshotId"
      
          ]
tsource_region = event["SourceRegion"]
tdescription
       = event["Description"
          ]
tresponse = ec2_client.copy_snapshot(
      nttDescription=description,

          ttSourceRegion=source_region,
      nttSourceSnapshotId=snapshot_id
t)

          
treturn {
      ntt"SnapshotId": response["SnapshotId"]
t}"
      FunctionName:

              Ref: LambdaName
      Handler: index.handler
      MemorySize: 128

            Role:
        Fn::If:
        - LambdaAssumeRoleNotSpecified
    
          - Fn::GetAtt:
          - LambdaRole
          - Arn
        - Ref:
       LambdaRoleArn
      Runtime: python3.7
      Timeout: 60
    Type: AWS::Lambda::Function

        LambdaRole:
    Condition: LambdaAssumeRoleNotSpecified
    Properties:

            AssumeRolePolicyDocument:
        Statement:
        - Action:
  
              - sts:AssumeRole
          Effect: Allow
          Principal:
 
                 Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'

            Path: /
      Policies:
      - PolicyDocument:
          Statement:

                  Action:
            - ec2:CopySnapshot
            Effect: Allow

                  Resource: '*'
          Version: '2012-10-17'
        PolicyName:
       CopySnapshotLambdaPolicy
    Type: AWS::IAM::Role
"
    Parameters:
    - ParameterValue: "{{LambdaAssumeRole}}"
      ParameterKey: "LambdaRoleArn"
    - ParameterValue: "CopySnapshotLambda-{{automation:EXECUTION_ID}}"
      ParameterKey: "LambdaName"
    Capabilities:
    - "CAPABILITY_IAM"
  name: "createDocumentStack"
- action: "aws:invokeLambdaFunction"
  inputs:
    FunctionName: "CopySnapshotLambda-{{automation:EXECUTION_ID}}"
    Payload: "{"SnapshotId": "{{SnapshotId}}", "SourceRegion": "{{SourceRegion}}"
      , "Description": "{{Description}}"}"
  name: "copySnapshot"
- action: "aws:deleteStack"
  inputs:
    StackName: "CopySnapshotStack{{automation:EXECUTION_ID}}"
  name: "deleteCloudFormationTemplate"
outputs:
- "copySnapshot.Payload"
