description: |
  ### Document name - AWSConfigRemediation-UpdateOpenSearchDomainSecurityGroups

  ## What does this document do?
  This runbook updates the AWS security group configuration on a given Amazon OpenSearch Service (Amazon OpenSearch) domain using the [UpdateDomainConfig](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-api.html#configuration-api-actions-updatedomainconfig) API.
  Please note, AWS security groups can only be applied to Amazon OpenSearch domains configured for Amazon Virtual Private Cloud (VPC) Access, not those configured for Public Access.

  ## Input Parameters
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * DomainName: (Required) The name of the Amazon OpenSearch Service domain for which you want to update security groups.
  * SecurityGroupList: (Required) The list of AWS security group IDs.

  ## Output Parameters
  * UpdateSecurityGroupsAndVerify.Output - Success message or failure exception.
assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: ^arn:(?:aws|aws-us-gov|aws-cn):iam::d{12}:role/[w+=,.@/-]+$
  DomainName:
    type: String
    description: (Required) The name of the Amazon OpenSearch Service domain for which you want to update security groups.
    allowedPattern: (d{12}/)?[a-z]{1}[a-z0-9-]{2,28}
  SecurityGroupList:
    type: StringList
    description: (Required) The list of AWS security group IDs.
    allowedPattern: ^sg-[0-9a-f]{1,17}$
outputs:
  - UpdateSecurityGroupsAndVerify.Output
mainSteps:
  - name: UpdateSecurityGroupsAndVerify
    action: "aws:executeScript"
    isEnd: true
    timeoutSeconds: 600
    description: |
      ## UpdateSecurityGroupsAndVerify
      Makes UpdateDomainConfig API call using Amazon OpenSearch domain name and security groups IDs and updates AWS security group configuration on Amazon OpenSearch domain and verifies its state.
      ## Outputs
      * Output: Success message or failure exception.
    inputs:
      Runtime: python3.8
      Handler: handler
      InputPayload:
        DomainName: "{{ DomainName }}"
        SecurityGroupIds: "{{ SecurityGroupList }}"
      Script: |-
        import boto3
        import re
        from botocore.config import Config

        config = Config(
            retries={
                "max_attempts": 10,
                "mode": "standard"
            }
        )

        opensearch_client = boto3.client("opensearch", config=config)

        def update_security_group_ids(domain_name, security_grp_list):
            return opensearch_client.update_domain_config(
                DomainName=domain_name, VPCOptions={"SecurityGroupIds": security_grp_list}
            )

        def verify_security_groups_ids_updated(domain_name, security_grp_ids):
            security_grp_list = opensearch_client.describe_domain(
                DomainName=domain_name
            )["DomainStatus"]["VPCOptions"]["SecurityGroupIds"]
            if sorted(security_grp_list) == sorted(security_grp_ids):
                return True
            return False

        def handler(event, context):
            domain_name = event["DomainName"]
            security_grp_ids = event["SecurityGroupIds"]
            domain_pattern = r"(d{12}/)?[a-z]{1}[a-z0-9-]{2,28}"
            if re.match(domain_pattern, domain_name):
                domain_name = domain_name.split("/")[-1]
            update_domain_response = update_security_group_ids(domain_name, security_grp_ids)['ResponseMetadata']
            update_status = verify_security_groups_ids_updated(domain_name, security_grp_ids)
            if update_status:
                return {
                    "output": {
                        "Message": "Verification of AWS security groups on Amazon OpenSearch domain is successful.",
                        "HTTPResponse": update_domain_response,
                    }
                }
            raise Exception(
                "VERIFICATION OF AWS SECURITY GROUPS ON AMAZON OPENSEARCH DOMAIN FAILED."
            )
    outputs:
      - Name: Output
        Selector: $.Payload.output
        Type: StringMap
