description: |
   ### Document name - AWSConfigRemediation-ReplaceIAMInlinePolicy

   ## What does this document do?
   The runbook replaces an inline AWS Identity and Access Management (IAM) policy with a replicated managed IAM policy. 
   For an inline policy attached to an IAM user, group, or role the inline policy permissions are cloned into a managed IAM policy. 
   The managed IAM policy will be added to the resource, and the inline policy is removed. AWS Config must be enabled in the AWS Region where you run this automation.

   ## Input Parameters
   * AutomationAssumeRole: (Required) The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that allows Systems Manager Automation to perform the actions on your behalf.
   * ResourceId: (Required) The ID of the IAM user, group, or role whose inline policy you want to replace.
   * InlinePolicyNames: (Optional) The list of inline IAM policies you want to replace. If not specified all inline IAM policies attached to the resource will be replaced.

   ## Output Parameters
   * ReplaceIamInlinePolicies.Output: The standard HTTP response from the ListRolePolicies or ListUserPolicies or ListGroupPolicies call.

assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that allows Systems Manager Automation to perform the actions on your behalf.
    allowedPattern: ^arn:(aws[a-zA-Z-]*)?:iam::d{12}:role/[w+=,.@/-]+$
  ResourceId:
    type: String
    description: (Required) The ID of the IAM user, group, or role whose inline policy you want to replace.
    allowedPattern: "^(AGPA|AIDA|AROA)[A-Z0-9+=,.@-_]{1,128}$"
  InlinePolicyNames:
    type: StringList
    description: (Optional) The list of inline IAM policies you want to replace. If not specified all inline IAM policies attached to the resource will be replaced.
    allowedPattern: "^$|^[a-zA-Z0-9+=,.@-_]*"
    default: []
outputs:
  - ReplaceIamInlinePolicies.Output
mainSteps:
  - name: ReplaceIamInlinePolicies
    action: "aws:executeScript"
    description: |
      ## ReplaceIamInlinePolicies
      Replace the inline IAM policy with an AWS managed policy on the resource you specify.
      ## Outputs
      * Output: The standard HTTP response from the ListRolePolicies or ListUserPolicies or ListGroupPolicies call.
    isEnd: true
    timeoutSeconds: 600
    inputs:
      Runtime: python3.7
      Handler: handler
      InputPayload:
        ResourceId: "{{ ResourceId }}"
        InlinePolicyNames: "{{ InlinePolicyNames }}"
      Script: |-
        import boto3
        import json

        def get_list_policies(iam_client, resourceType, resourceName):
          policy_response = {}
          if resourceType == "AWS::IAM::Role":
            policy_response = iam_client.list_role_policies(RoleName=resourceName)
          elif resourceType == "AWS::IAM::Group":
            policy_response = iam_client.list_group_policies(GroupName=resourceName)
          elif resourceType == "AWS::IAM::User":
            policy_response = iam_client.list_user_policies(UserName=resourceName)
          return policy_response

        def is_inline_policy_exists(policy_response, inline_policy_names):
          if policy_response["PolicyNames"]:
            if not inline_policy_names or set(inline_policy_names).intersection(policy_response["PolicyNames"]):
              return False 
          return True

        def get_select_resource_config(config_client, resource_id):
          select_query = "SELECT * WHERE resourceType in ('AWS::IAM::Group','AWS::IAM::Role','AWS::IAM::User') and resourceId = '{}'"
          select_query = select_query.format(resource_id)
          return config_client.select_resource_config(Expression=select_query)

        def update_role_inline_policies(iam_client, resourceName, inline_policy_names):
          #update Role changes
          policy_list = iam_client.list_role_policies(RoleName=resourceName)
          for policy_name in policy_list['PolicyNames']:
            if not inline_policy_names or policy_name  in inline_policy_names:
              policy_name_converted = policy_name + "_converted"
              policy_details = iam_client.get_role_policy(RoleName=resourceName,PolicyName=policy_name)
              create_policy_Response = iam_client.create_policy(PolicyName=policy_name_converted,PolicyDocument=json.dumps(policy_details['PolicyDocument']),Description="Converted inline policy to managed policy")
              iam_client.attach_role_policy(RoleName=resourceName, PolicyArn=create_policy_Response['Policy']['Arn'])
              iam_client.delete_role_policy(RoleName=resourceName, PolicyName=policy_name)

        def update_group_inline_policies(iam_client, resourceName, inline_policy_names):
          #update Group changes
          policy_list = iam_client.list_group_policies(GroupName=resourceName)
          for policy_name in policy_list['PolicyNames']:
            if not inline_policy_names or policy_name in inline_policy_names:
              policy_name_converted = policy_name + "_converted"
              policy_details = iam_client.get_group_policy(GroupName=resourceName,PolicyName=policy_name)
              create_policy_Response = iam_client.create_policy(PolicyName=policy_name_converted,PolicyDocument=json.dumps(policy_details['PolicyDocument']),Description="Converted inline policy to managed policy")
              iam_client.attach_group_policy(GroupName=resourceName, PolicyArn=create_policy_Response['Policy']['Arn'])
              iam_client.delete_group_policy(GroupName=resourceName, PolicyName=policy_name)

        def update_user_inline_policies(iam_client, resourceName, inline_policy_names):
          #update User changes
          policy_list = iam_client.list_user_policies(UserName=resourceName)
          for policy_name in policy_list['PolicyNames']:
            if not inline_policy_names or policy_name in inline_policy_names:
              policy_name_converted = policy_name + "_converted"
              policy_details = iam_client.get_user_policy(UserName=resourceName,PolicyName=policy_name)
              create_policy_Response = iam_client.create_policy(PolicyName=policy_name_converted,PolicyDocument=json.dumps(policy_details['PolicyDocument']),Description="Converted inline policy to managed policy")
              iam_client.attach_user_policy(UserName=resourceName, PolicyArn=create_policy_Response['Policy']['Arn'])
              iam_client.delete_user_policy(UserName=resourceName, PolicyName=policy_name)

        def handler(event, context):
          config_client = boto3.client("config")
          iam_client = boto3.client("iam")
          resource_id = event["ResourceId"]
          inline_policy_names = event["InlinePolicyNames"]
          
          select_response = get_select_resource_config(config_client, resource_id)

          resource_type = json.loads(select_response['Results'][0])['resourceType']
          resource_name = json.loads(select_response['Results'][0])['resourceName']
          resource = ""
          if resource_type == 'AWS::IAM::Role':
            update_role_inline_policies(iam_client, resource_name, inline_policy_names)
            resource = "Role"
          elif resource_type == 'AWS::IAM::Group':
            update_group_inline_policies(iam_client, resource_name, inline_policy_names)
            resource = "Group"
          elif resource_type == 'AWS::IAM::User':
            update_user_inline_policies(iam_client, resource_name, inline_policy_names)
            resource = "User"

          list_policies_response = get_list_policies(iam_client, resource_type, resource_name)
          if is_inline_policy_exists(list_policies_response, inline_policy_names):
              return {
                  "output": {
                      "Message": "Verification of replacing inline policies for AWS IAM {} {} is successful.".format(resource.lower(), resource_name),
                      "HTTPResponse": list_policies_response["ResponseMetadata"]
                  }
              }
          raise Exception(
              "VERIFICATION FAILED. REPLACING INLINE POLICIES FOR AWS IAM {} {} IS UNSUCCESSFUL.".format(resource.upper(), resource_name)
          )
    outputs:
      - Name: Output
        Selector: $.Payload.output
        Type: StringMap
